# Custom Language File for Launcher Customizer

[ejs.app]
title = "짱슬이서버"

[ejs.landing]
mediaChzzkURL = "https://chzzk.naver.com/5b7a9831e616af0fad2787c72012e6e1"
mediaTwitterURL = "#"
mediaInstagramURL = "https://www.instagram.com/zzs2eul"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/tYvTYSznmH"

[ejs.settings]
sourceGithubLink = "https://github.com/imtaeyang/ZZS2eul"
supportLink = "https://github.com/imtaeyang/ZZS2eul/issues"

[ejs.welcome]
welcomeHeader = "짱슬이서버에 오신 것을 환영합니다!"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
